import PDFDocument from 'pdfkit';
import { uploadReportToS3, getPresignedUrl } from '../services/s3Service.js';
import Vitals from '../models/Vitals.js';
import Report from '../models/Report.js';
import Patient from '../models/Patient.js';
import User from '../models/User.js';
import * as fs from 'fs';

// @desc    Generate and save patient report
// @route   POST /api/report/generate/:patientId
// @access  Private (Doctor)
export const generateReport = async (req, res) => {
  const patientId = req.params.patientId;
  
  try {
    const user = await User.findById(patientId);
    if (!user) return res.status(404).json({ message: 'Patient User not found' });

    const vitalsHistory = await Vitals.find({ patientId }).sort({ timestamp: -1 }).limit(10);
    
    const doc = new PDFDocument();
    let buffers = [];
    doc.on('data', buffers.push.bind(buffers));
    
    doc.fontSize(20).text(`Swasthya Setu - Patient Health Report`, { align: 'center' });
    doc.moveDown();
    doc.fontSize(14).text(`Patient Name: ${user.name}`);
    doc.text(`Patient ID: ${patientId}`);
    doc.text(`Generated By: ${req.user.name} (${req.user.role})`);
    doc.moveDown();
    
    vitalsHistory.forEach((v, index) => {
      doc.fontSize(12).text(`${index + 1}. Date: ${new Date(v.timestamp).toLocaleString()}`);
      doc.text(`   HR: ${v.heartRate} bpm | Temp: ${v.temperature}°C | SpO2: ${v.spo2}%`);
      if (v.anomalyFlag) {
        doc.fillColor('red').text(`   Alert: ${v.aiAnalysis}`).fillColor('black');
      }
      doc.moveDown();
    });
    doc.end();

    doc.on('end', async () => {
      const pdfBuffer = Buffer.concat(buffers);
      const fileName = `report_${patientId}_${Date.now()}.pdf`;
      let fileUrl = '';
      
      try {
        fileUrl = await uploadReportToS3(patientId, pdfBuffer, fileName);
      } catch (e) {
        console.error('S3 Upload failed, falling back to local simulation', e.message);
        fileUrl = `https://mock-s3-bucket.s3.amazonaws.com/${fileName}`; // Mock URL fallback
      }

      const report = await Report.create({
        patientId,
        doctorId: req.user._id,
        title: `Vitals Summary Report - ${new Date().toLocaleDateString()}`,
        pdfUrl: fileUrl, // Now stores the S3 KEY
        summary: `Report generated based on last ${vitalsHistory.length} vitals readings.`
      });

      res.status(201).json(report);
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Get reports
// @route   GET /api/report
// @access  Private
export const getReports = async (req, res) => {
  try {
    let reports;
    if (req.user.role === 'Doctor' || req.user.role === 'Admin') {
      reports = await Report.find().populate('patientId', 'name email').sort({ createdAt: -1 });
    } else {
      reports = await Report.find({ patientId: req.user._id }).populate('doctorId', 'name').sort({ createdAt: -1 });
    }

    // Convert keys to Signed URLs for private viewing
    const reportsWithUrls = await Promise.all(reports.map(async (report) => {
      const reportObj = report.toObject();
      if (reportObj.pdfUrl && !reportObj.pdfUrl.startsWith('http')) {
        reportObj.pdfUrl = await getPresignedUrl(reportObj.pdfUrl);
      }
      return reportObj;
    }));

    res.json(reportsWithUrls);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Upload user report manually
// @route   POST /api/report/upload
// @access  Private (Patient/Doctor)
export const uploadReport = async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ message: 'No file uploaded' });
    }
    
    // Patient can upload for themselves, Doctor needs to provide patientId in body
    const patientId = req.user.role === 'Doctor' ? req.body.patientId : req.user._id;
    if (!patientId) {
      return res.status(400).json({ message: 'Patient ID is required' });
    }

    const { buffer, originalname } = req.file;
    const fileName = `manual_${patientId}_${Date.now()}_${originalname}`;
    
    let fileUrl = '';
    try {
      fileUrl = await uploadReportToS3(patientId, buffer, fileName);
    } catch (e) {
      console.error('S3 Upload failed, falling back to local simulation', e.message);
      fileUrl = `https://mock-s3-bucket.s3.amazonaws.com/${fileName}`; // Mock URL fallback
    }

    const report = await Report.create({
      patientId,
      doctorId: req.user.role === 'Doctor' ? req.user._id : undefined,
      title: req.body.title || `Uploaded Report - ${originalname}`,
      pdfUrl: fileUrl,
      summary: req.body.summary || `Manually uploaded report document.`,
    });

    res.status(201).json(report);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
