import mongoose from 'mongoose';

const reportSchema = new mongoose.Schema({
  patientId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  doctorId: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }, // Optional, if generated by doctor
  title: { type: String, required: true },
  pdfUrl: { type: String },
  summary: { type: String },
  createdAt: { type: Date, default: Date.now }
});

export default mongoose.model('Report', reportSchema);
